trigger:
- main

variables:
  vmImageName: 'windows-latest'
  projectName: 'SampleApp'

stages:
  - stage: Build
    displayName: Build Ionic - Android projects
    jobs:
      # Debug build
      - job: Build_Ionic_Android_Debug
        variables:
          - name: buildConfiguration
            value: Debug
        displayName: Build Debug
        pool:
          vmImage: $(vmImageName)
        steps:
          - template: ionic-android-debug-build.yml

      # Release build
      - job: Build_Ionic_Android_Release
        variables:
          - group: SampleApp-Release
          - name: buildConfiguration
            value: Release
        displayName: Build Release
        pool:
          vmImage: $(vmImageName)
        steps:
          - template: ionic-android-release-build.yml
            parameters:
              keystoreFileName: 'sampleapp-release-key.keystore'
              keystorePassword: $(keystorePassword)
              keyAlias: $(keyAlias)
              keyPassword: $(keyPassword)

    - stage: Deploy
      displayName: Deploy Debug and Release Apps to App Center
      dependsOn: Build
      jobs:
        - deployment: Deploy_Android_Debug
          variables:
            buildConfiguration: Debug
          displayName: Deploy Android - Debug App
          pool:
            vmImage: $(vmImageName)
          environment: Staging
          strategy:
            runOnce:
              deploy:
                steps:
                  - template: ionic-android-debug-deploy.yml
                    parameters:
                      appCenterServiceConnection: 'App Center Integration for Sample App'
                      appSlug: '{username or org name}/{app name in App Center}'
                      appFile: '$(Pipeline.Workspace)/$(projectName)/app-$(buildConfiguration).apk'
                      releaseNotes: 'Debug App'